### ISSUE TITLE
Auto-adds Pike Terraform delimiter at the end of the README.md by default. - Fix: Pike delimiters not found in Readme 

### ISSUE THREAD

**Issue by good92** [JamesWoolfenden/pike#21]
**Is your feature request related to a problem? Please describe.**
Auto-adds Pike Terraform delimiter at the end of the README.md by default.

**Comment by good92** [comment]
yes, it will help for automation

**Comment by JamesWoolfenden** [comment]
theres is now a -A autoappend flag that does this

**Comment by good92** [comment]
Wow, that was fast, many thanks. I will test that tomorrow.

**Comment by JamesWoolfenden** [comment]
Ok to close?
