### ISSUE TITLE
FEATURE - Run pike recursively to scan sub folders

### ISSUE THREAD

**Issue by nicholas-marchini** [JamesWoolfenden/pike#36]
**Is your feature request related to a problem? Please describe.**
We have a GitHub repo for terraform but with multiple sub-folders for managing different state files. We can only have one role that is assumed by the GH runner so we need to run Pike recursively against the whole GH repo to produce a policy that will allow us to execute TF again any sub folder. 

**Describe the solution you'd like**
run pike to scan all sub folders

**Describe alternatives you've considered**
Running if for 39 directories individually and manually combining the output

**Comment by JamesWoolfenden** [comment]
Happy to take a PR if you fancy developing it @NP-compete ?
