### ISSUE TITLE
Nothing Major, but version is not shown with v or version

### ISSUE THREAD

**Issue by Woolersuk** [JamesWoolfenden/pike#46]
Loving the tool, brilliant thanks!

**Describe the bug**
Just one minor thing, on Linux or Windows, if I run pike v, or pike version, the output is blank...

**To Reproduce**
run pike v, or pike version in linux or windows

**Comment by Woolersuk** [comment]
```
pike -v
Incorrect Usage: flag provided but not defined: -v

pike version

pike v

pike -version
Incorrect Usage: flag provided but not defined: -version
```

**Comment by JamesWoolfenden** [comment]
strange, seems everything works for me with the latest:
```
C:\WINDOWS\system32> pike -v
pike version v0.2.42
C:\WINDOWS\system32> pike --v
pike version v0.2.42
C:\WINDOWS\system32> pike --version
pike version v0.2.42
C:\WINDOWS\system32> pike version
v0.2.42
```

How are you installing pike?

**Comment by Woolersuk** [comment]
Thanks for getting back, I'm just downloading the latest binary & using that.

v0.2.67

**Comment by JamesWoolfenden** [comment]
ah replicated!

**Comment by JamesWoolfenden** [comment]
here's what I think happened, if you agree/test it then ill close. The latest version of goreleaser deprecated a variable i was using to version the binary, setting the version="". This meant that the cli framework said there was no -v flag or version (a LIE i tell YA). Any way i'm calmer now and I just get the latest tag from git instead.

**Comment by Woolersuk** [comment]
Brilliant, many thanks!! - I can confirm on both mine it's now showing properly

Sorry for the delay!

**Comment by Woolersuk** [comment]
I'll close it off :)
