### ISSUE TITLE
ecs:ModifyCluster does not exist

### ISSUE THREAD

**Issue by Woolersuk** [JamesWoolfenden/pike#58]
**Describe the bug**
ecs:ModifyCluster - this is not an existing permission, perhaps this should be set to ecs:UpdateCluster

**To Reproduce**

Create a resource such as resource "aws_ecs_task_definition" "task" in terraform

**Expected behavior**
Permissions are correct

**Screenshots**
![image](https://github.com/JamesWoolfenden/pike/assets/50249037/04bcc98c-b320-4036-9db5-60f05f9f05bd)

Cheers

**Comment by JamesWoolfenden** [comment]
quite right that isnt right. fixed
