### ISSUE TITLE
SNS:CreateTopic missing + possibly others..

### ISSUE THREAD

**Issue by Woolersuk** [JamesWoolfenden/pike#60]
**Describe the bug**
Hello good sir...

I added a resource for SNS notifications & noticed I didn't have permission, when I ran a pike scan, this was not picked up...

**To Reproduce**
in a TF repo, add in something like this:

module "mail_notification" {
  source  = "geekcell/sns-email-notification/aws"
  version = "1.0.2"

  email_addresses = ["myemail@whatever.com"]
  name            = "My_Alert"
}

**Expected behavior**
SNS permissions are shown..

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
In the end, I had to add the following permissions using the module above if it helps!

                "SNS:CreateTopic",
                "SNS:DeleteTopic",
                "SNS:GetSubscriptionAttributes",
                "SNS:GetTopicAttributes",
                "SNS:ListTagsForResource",
                "SNS:Publish",
                "SNS:SetTopicAttributes",
                "SNS:Subscribe",
                "SNS:TagResource",
                "SNS:Unsubscribe",

**Comment by JamesWoolfenden** [comment]
ta IWTA

**Comment by JamesWoolfenden** [comment]
ok the perms for topic subscription were empty:
      "SNS:Subscribe",
      "SNS:GetSubscriptionAttributes",
      "SNS:Unsubscribe"

were missing.
So only  "SNS:Publish" is different. I'm not seeing this as required for making an snstopic/subscription maybe you had other resources/actions that required it?

**Comment by JamesWoolfenden** [comment]
i pushed a new version

**Comment by JamesWoolfenden** [comment]
nothing obvious without seeing the code, not really expecting publish unless you actually try an use the topic

**Comment by Woolersuk** [comment]
Sorry, yes, the [module ](https://registry.terraform.io/modules/geekcell/sns-email-notification/aws/latest?tab=resources) I'm using creates these:

    aws_sns_topic.main
    aws_sns_topic_subscription.main

**Comment by JamesWoolfenden** [comment]
i dont think SNS:Publish is required, ok to close this?

**Comment by Woolersuk** [comment]
Yeah.
