### ISSUE TITLE
Unable to Get the Complete Policy Permission Details - pike version v0.2.104

### ISSUE THREAD

**Issue by macbash** [JamesWoolfenden/pike#61]
**Describe the bug**

Unable to Get the Complete Policy Permission Details required for the specific terraform action ( especially in EC2, EKS,S3, SNS )

**To Reproduce**

./pike scan -d . <Repo Containing the terraform files >

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] - MAC
- Version [e.g. 22] - v0.2.104

**Smartphone (please complete the following information):**
 - NA

**Additional context**

**Comment by JamesWoolfenden** [comment]
hi @macbash what terraform were you pointing pike at that failed?
