### ISSUE TITLE
Submodules of downloaded modules are not found

### ISSUE THREAD

**Issue by jkritzen** [JamesWoolfenden/pike#64]
**Describe the bug**
When using a complex root module, then the path to sub modules are not found within the downloaded modules below .terraform.

**To Reproduce**

docker run --tty --volume `pwd`:/tf jameswoolfenden/pike scan -d /tf

1. Use a module with "submodules" directories, example:
├── modules
│   ├── container-definition
│   │   ├── main.tf
│   │   ├── MODULE.md
│   │   ├── outputs.tf
│   │   ├── README.md
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── ecs-cluster
│   │   ├── main.tf
│   │   ├── MODULE.md
│   │   ├── outputs.tf
│   │   ├── README.md
│   │   ├── variables.tf
│   │   └── versions.tf
│   ├── ecs-service
│   │   ├── main.tf
│   │   ├── MODULE.md
│   │   ├── outputs.tf
│   │   ├── README.md
│   │   ├── variables.tf
│   │   └── versions.tf
│   └── ecs-task
│       ├── main.tf
│       ├── MODULE.md
│       ├── outputs.tf
│       ├── README.md
│       ├── templates
│       │   └── ecs_task_execution_role.json
│       ├── variables.tf
│       └── versions.tf
├── main.tf
├── outputs.tf
├── README.md
├── variables.tf
└── versions.tf

2. run pike scan
3. The debug output will state:
7:05PM DBG getTF folder /tf/modules/ecs-task can't be found
7:05PM DBG getTF folder /tf/modules/ecs-service can't be found
7:05PM DBG getTF folder /tf/modules/ecs-cluster can't be found
7:05PM DBG getTF folder /tf/modules/ecs-task can't be found
7:05PM DBG getTF folder /tf/modules/ecs-service can't be found

**Expected behavior**
pike should find the submodules within the downloaded module below .terraform/modules/container.ecs_cluster:
└── modules
    ├── container-definition
    ├── ecs-cluster
    ├── ecs-service
    └── ecs-task
        └── templates

**Desktop (please complete the following information):**

- OS: Linux
- Docker Version: jameswoolfenden/pike:latest

**Additional context**

When i link the submodule directories to the modules directory, pike will add needed IAM permissions to the policy:

eg ln-s .terraform/modules/container.ecs_cluster/modules/ecs-service modules/ecs-service within the root of the terraform root module.

Hope this is easy to fix,
Jörg

**Comment by JamesWoolfenden** [comment]
Hi @jkritzen thanks for tkaing the time to log your issue.
Im not managing replicating this, maybe something more subtle in your repos structure. If you can share a sample project that fails this way I can investigate and remedy this.  I dont scan the contents of the .terraform folder as pike is designed to be run statically and so if you use modules pike will download them itself and scan them (if theyre local or from the registry). I think the error your seeing is becuase they are neither?

**Comment by duje-begonja-rdx** [comment]
First of all, great tool that really helps narrow down IAM permissions and make security as tight as possible.

Describe the bug
When using official terraform modules for AWS that are referenced inside our reusable module pike complains it can't find modules.

To Reproduce
Directory structure:
| modules
|--> eks-cluster
| |--> main.tf (one module uses `"terraform-aws-modules/vpc/aws"` and other modules uses `"terraform-aws-modules/eks/aws"`)
|--> cloudwatch-alarms
||--> main.tf
| actual-cluster
| |--> main.tf
| |--> outputs.tf ....

When referencing module `cloudwatch-alarms` pike finds it and reads actual resources. When referencing module `eks-cluster` which actually further references two official modules those official modules can't be found even though downloaded under `.terraform` folder.

Screnshoot 1 shows that modules are correctly
![Screenshot 2023-12-11 at 08 48 15](https://github.com/JamesWoolfenden/pike/assets/108268552/abfde553-6c73-430a-8db5-ecb644b4c892)

Here is error I receive:
```
8:34AM DBG getTF folder terraform-aws-modules/iam/aws/modules/iam-role-for-service-accounts-eks can't be found
8:34AM DBG getTF folder terraform-aws-modules/s3-bucket/aws can't be found
8:34AM DBG getTF folder terraform-aws-modules/s3-bucket/aws can't be found
8:34AM DBG getTF folder terraform-aws-modules/iam/aws/modules/iam-policy can't be found
8:34AM DBG getTF folder terraform-aws-modules/iam/aws/modules/iam-role-for-service-accounts-eks can't be found
8:34AM DBG getTF folder terraform-aws-modules/iam/aws/modules/iam-role-for-service-accounts-eks can't be found
8:34AM DBG getTF folder terraform-aws-modules/route53/aws/modules/zones can't be found
8:34AM DBG getTF folder terraform-aws-modules/acm/aws can't be found
8:34AM DBG getTF folder terraform-aws-modules/iam/aws/modules/iam-role-for-service-accounts-eks can't be found
8:34AM DBG getTF folder terraform-aws-modules/s3-bucket/aws can't be found
8:34AM DBG getTF folder terraform-aws-modules/vpc/aws can't be found ...
```

So seems like problem is with every official terraform module and with modules referencing modules.

Desktop (please complete the following information):
OS: mac ARM
Pike version: v0.3.1

Additional context
Please provide workaround if possible if this is actual behaviour and not me using it the wrong way.

Thanks

**Comment by duje-begonja-rdx** [comment]
Starting with empty "state":

![Screenshot 2023-12-11 at 10 44 42](https://github.com/JamesWoolfenden/pike/assets/108268552/61331d68-9e6d-40c1-9dc4-3a9cddcca31a)

When I run `pike scan -d . -i` this is dir structure:

![Screenshot 2023-12-11 at 10 46 14](https://github.com/JamesWoolfenden/pike/assets/108268552/237f706f-44e7-4804-b113-209fd82045a2)

When I run option 2 with terraform init:

![Screenshot 2023-12-11 at 10 48 04](https://github.com/JamesWoolfenden/pike/assets/108268552/0e6bb792-c2f1-4d67-aba2-3c163cb97772)

So unlike your case, I don't end up with folder `.external_modules`.

```
% pike --version
pike version v0.3.1
```

**Comment by JamesWoolfenden** [comment]
if you have private modules you need to use tf init locally first

**Comment by duje-begonja-rdx** [comment]
downloaded new pike version.
Ran these cmds:
```
terraform init
pike scan -d .
```

I get this error (one of them):
`11:20AM INF local module scan getTF, folder terraform-aws-modules/eks/aws can't be found, may not be local path`
`.terraform` folder created
`.external_modules` folder not created

**Comment by JamesWoolfenden** [comment]
> downloaded new pike version. Ran these cmds:
> 
> ```
> terraform init
> pike scan -d .
> ```
> 
> I get this error (one of them): `11:20AM INF local module scan getTF, folder terraform-aws-modules/eks/aws can't be found, may not be local path` `.terraform` folder created `.external_modules` folder not created

The only way you'll get submodules scanned is if you do tf init before or use the -i flag

**Comment by duje-begonja-rdx** [comment]
> The only way you'll get submodules scanned is if you do tf init before or use the -i flag
Both CI with Linux runner and local macOS ARM laptop have same issue. No matter what combination I run (option 2 or 3) in "fresh" directory I still get same errors. (no `.external_modules` folder gets created)

**Comment by JamesWoolfenden** [comment]
that was my mistake, I was confused with another tool i wrote Pike just wraps terraform and uses init so it'll downloads to .terraform

**Comment by duje-begonja-rdx** [comment]
are there any further steps I can try to troubleshoot issue?

**Comment by jasonhuling** [comment]
I'm having this issue in pike version v0.3.6. The modules are private, so I'm running the following:
```
terraform init
pike scan -d .
```
Just getting a lot of these logs and nothing generated because the AWS resources are in the submodule:
```
INF local module scan getTF, folder app.terraform.io/<org>/iam/aws/modules/<submodule> can't be found, may not be local path
```

**Comment by nikitacr7** [comment]
I have the same behavior as @jasonhuling . I use submodules of "terraform-aws-modules/route53/aws//modules/records" and gettings the same errors: 

```
3:34PM DBG downloaded route53_records_with_default_configuration
3:34PM INF local module scan getTF, folder terraform-aws-modules/route53/aws/modules/records can't be found, may not be local path
3:34PM INF Provider route53 Type module not found
```

@JamesWoolfenden any suggestions?
