### ISSUE TITLE
Create pre-commit hook to generate policy file

### ISSUE THREAD

**Issue by JamesWoolfenden** [JamesWoolfenden/pike#7]
Diff against existing policy 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by antonbabenko** [comment]
👍 I was thinking about adding such a hook into https://github.com/antonbabenko/pre-commit-terraform since I discovered `pike`, but I don't have time to do that myself.

I will subscribe to this issue to see if anyone wants to work on it, and I can guide or explain how `pre-commit-terraform` works if necessary.

**Comment by JamesWoolfenden** [comment]
i think it already pretty much exists - there's already a hooks that runs
any pike command
  - repo: https://github.com/jameswoolfenden/pike
    rev: v0.1.61
    hooks:
      - id: pike-docs-go
        args: ["-i", "-d", ".", "readme"]

But it can run any pike command. I was thinking of having a standard
command that outputs all the tf thats required for the new role and policy
to a .pike folder? WDYT?

**Comment by antonbabenko** [comment]
This runs `pike` once, but I was more thinking about `how to run pike in all places where it makes sense in the whole git repository` - e.g. in root, `./examples/`, `./modules/`. And update multiple READMEs in all the places.

This is the standard behavior of all `pre-commit-terraform` hooks.

**Comment by JamesWoolfenden** [comment]
ive put in the -w flag which writes out the policy/role required into .pike folder
