### ISSUE TITLE
pike scan says DBG: provider was not found

### ISSUE THREAD

**Issue by TwiggyWan** [JamesWoolfenden/pike#72]
Hello and thanks for the tool

**Describe the bug**
When I run `pike scan -d .` it says `DBG: provider was not found`

I have a couple providers that do not work : 
This one comes from a module defined in separate file
```
module "eks_cluster" {
  source = "git::ssh://git@MYREPO?ref=v1.12.1"

  cluster_name        = var.cluster_name
  vpc_id              = aws_vpc.main.id
  public_subnets_ids  = [for s in aws_subnet.public : s.id]
  private_subnets_ids = [for s in aws_subnet.private : s.id]
}
----
provider "kubernetes" {
  host                   = module.eks_cluster.api_endpoint
  cluster_ca_certificate = base64decode(module.eks_cluster.kubeconfig_cert_auth_data)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    args        = ["eks", "get-token", "--cluster-name", module.eks_cluster.cluster_name]
    command     = "aws"
  }
}

```

For this one I have only a provider block : 
```
provider "healthchecksio" {
  api_url = "https://healthchecks.tooling.owkin.com/api/v1"
  api_key = data.sops_file.terraform_secrets.data["healthchecks_api_key"]
}

```

Here is excerpt from versions.tf 

```
terraform {
  required_version = "~> 1.7"

  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.21"
    }
    healthchecksio = {
      source  = "kristofferahl/healthchecksio"
      version = "~> 1.10"
    }
  }
}

```

**To Reproduce**
Not sure, you could add a resource file like this : 

```
resource "kubernetes_config_map" "aws_auth_cm" {
  metadata {
    name      = "aws-auth"
    namespace = "kube-system"
  }

  data = {}

  depends_on = [
    module.eks_cluster
  ]
}
```

**Expected behavior**
I don't really know if that's bug or feature request.

IMHO two things could happen:
Either Pike finds the provider and either scans permissions or tells me resource X is not implemented
Or there is some kind of option to pike scan to tell it where to go read the provider code and it's up to me to point it towards it

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: linux
- Browser : N/A
- pike Version:  v0.3.11

**Additional context**
N/A

Many thanks

**Comment by JamesWoolfenden** [comment]
Hi @TwiggyWan thanks for the feedback. So a few things are going on here.  First is that your module eks is not downloadable as its private so I cant scan it as I cant pull it, If you tf init and run it will work. The other thing is the the other providers are not supported for IAM so would result in no IAM policy generated. There could be some better error messages so ill see if I can fix (have added) those. You're not seeing the errors raised due to your mix of private modules and unsupported providers .

**Comment by TwiggyWan** [comment]
Hi @JamesWoolfenden ,

> First is that your module eks is not downloadable as its private so I cant scan it as I cant pull it, If you tf init and run it will work.

You are right it does work and i did not notice the `-i` switch.

Couple questions about it : 
- can i write some .pikerc file to say i always want to do -i ? (or should i do some alias)
- the DBG log about init is printed only when terraform init completes, could it print before / can pike pass tf init stdout to the terminal?
- if i intentionally break my aws profile to make terraform init fail the DBG log about pike doing tf init goes away but no failure is printed. is this a known bug?

> The other thing is the the other providers are not supported for IAM so would result in no IAM policy generated.

So  : `DBG Provider XXX was not found' -> either provider is private OR does not require any IAM rules

 `DBG Provider XXX not implemented` -> pike knows it requires IAM rules but it's not done yet

yes?

Last question, I notice a difference in scan output from my project vs from my module : eg.

project : 

```
        {
            "Sid": "VisualEditor3",
            "Effect": "Allow",
            "Action": [
                "eks:CreateAddon",
                "eks:CreateCluster",
                "eks:DeleteAddon",
                "eks:DeleteCluster",
                "eks:DescribeAddon",
                "eks:DescribeAddonVersions",
                "eks:DescribeCluster",
                "eks:ListAddons",
                "eks:ListTagsForResource",
                "eks:UpdateAddon",
                "eks:UpdateClusterConfig"
            ],
            "Resource": [
                "*"
            ]
        },

```

module : 

```
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "eks:CreateCluster",
                "eks:DeleteCluster",
                "eks:DescribeCluster",
                "eks:ListTagsForResource",
                "eks:UpdateClusterConfig"
            ],
            "Resource": [
                "*"
            ]
        },

```

Do I have a way to increase verbosity to find out which permission or which statement comes from a specific tf file?

If you need me to write more issues about all those questions i'll be happy to.
