### ISSUE TITLE
Missed ec2:DescribeSecurityGroupRules

### ISSUE THREAD

**Issue by cs1nwx** [JamesWoolfenden/pike#73]
**Describe the bug**
Running pike against some of our terraform I noticed the IAM permission ec2:DescribeSecurityGroupRules was missing.

**To Reproduce**
I expect this is because we are using the aws_security_group_rule resource instead of inline security group rules.

**Expected behavior**
Expected ec2:DescribeSecurityGroupRules in pike output

**Comment by JamesWoolfenden** [comment]
indeed, thanks for taking the time to log it. Resolved in v0.3.17
