### ISSUE TITLE
Unable to install via go install

### ISSUE THREAD

**Issue by landon-orr-anchor** [JamesWoolfenden/pike#77]
**Describe the bug**
When installing pike via `go install  github.com/jameswoolfenden/pike@latest`, I receive the following error:
```
go: github.com/jameswoolfenden/pike@latest (in github.com/jameswoolfenden/pike@v0.3.26):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**To Reproduce**

1. Run `go install  github.com/jameswoolfenden/pike@latest`

**Expected behavior**
I expect this to install successfully.

- OS: Reproduced on Debian and Ubuntu

**Additional context**
I've replicated this on multiple machines and had others test this out as well. Looks like this broke in `v0.3.21` as I'm able to install prior releases via go install but anything after `v0.3.20` returns this error.

**Comment by JamesWoolfenden** [comment]
thanks for taking the time to log this. will investigate

**Comment by JamesWoolfenden** [comment]
fixed in latest release. Let me know if it works for you
